### ISSUE TITLE
When will the other versions be released?

### ISSUE THREAD

**Issue by Omgise** [unilock/LegacyFixes#1]

**Comment by unilock** [comment]
When I remember, mostly :p

I'll go ahead and make a release for v1.7.1 now.

**Comment by Omgise** [comment]
Thank you :p

**Comment by li654300306** [comment]
I know the comments below are not very good, but I urgently need your version 1.19.2 Better WaystonesMenu., I'm not sure whether you are a countrymen, so I left a message on mc encyclopedia, imploring you

**Comment by unilock** [comment]
@li654300306 I don't know what "mc encyclopedia" is, nor do I think of myself as a countryman, but here's (what should be) the latest build of my 1.19.2 version of BetterWaystonesMenu for Forge: [BetterWaystonesMenu-1.2.0+mc1.19.2.jar](https://github.com/unilock/BetterWaystonesMenu/releases/download/1.2.0%2Bmc1.19.2/BetterWaystonesMenu-1.2.0+mc1.19.2.jar)

I'll publish a release on the GitHub repo, too.

**Comment by li654300306** [comment]
Thank you for your generous sharing,

**Comment by li654300306** [comment]
Can I publish your version 1.19.2 on the MCMOD website? It will indicate the author because many people do not know how to operate GitHub. Do you think it's okay?
